repos:
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
        exclude: '(^.vscode/)'
      - id: pretty-format-json
        exclude: '(^.vscode/)'
        args:
          - --autofix
          - --indent
          - '2'
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        args: ['--profile', 'black']
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: uv run flake8 src
        language: system
        pass_filenames: false
        always_run: true
        args: ['--ignore=E203,E501,W503']
