name: Bug Report
description: Report a bug in the Python codebase
title: "[BUG]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened?
      placeholder: Clear and concise description of the bug
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Import '...'
        2. Call function '...'
        3. See error
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Python Version
      placeholder: e.g., 3.9.0
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Message
      description: If applicable, paste the error message or traceback
      render: shell

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
